//************************//
 //  [CAJERO AUTOMATICO]  //
//***********************//
package proyectos.banco.Gui;

import javax.swing.JOptionPane;
import Sistema.SistemaPeruBank;

/**
 *
 * @author jose vilcabana
 */
public class InterfazBanco extends javax.swing.JFrame {
    
    //  [variable local]  //
    boolean OpcionDepositar = false;
    boolean OpcionRetirar = false;
    String NuevoNumero;
    double NuevaCantidad = 0;
    SistemaPeruBank atm = new SistemaPeruBank();

    /**
     * Creates new form InterfazBanco
     */
    public InterfazBanco() {
        initComponents();
        this.setLocationRelativeTo(null);
        txt_Nombre.setText(" ");
        txt_Cantidad.setText(" ");
        
        Panel_Opcion.setVisible(false);
        
        Bnt_Depositar.setEnabled(false);
        Bnt_Retirar.setEnabled(false);
        Bnt_Salir.setEnabled(false);
        
        Bnt_1.setEnabled(false);
        Bnt_2.setEnabled(false);
        Bnt_3.setEnabled(false);
        Bnt_4.setEnabled(false);
        Bnt_5.setEnabled(false);
        Bnt_6.setEnabled(false);
        Bnt_7.setEnabled(false);
        Bnt_8.setEnabled(false);
        Bnt_9.setEnabled(false);
        Bnt_0.setEnabled(false);
        
        Bnt_Cancelar.setEnabled(false);
        Bnt_Borrar.setEnabled(false);
        Bnt_Aceptar.setEnabled(false);



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        Bnt_2 = new javax.swing.JButton();
        Bnt_3 = new javax.swing.JButton();
        Bnt_1 = new javax.swing.JButton();
        Bnt_4 = new javax.swing.JButton();
        Bnt_5 = new javax.swing.JButton();
        Bnt_6 = new javax.swing.JButton();
        Bnt_7 = new javax.swing.JButton();
        Bnt_8 = new javax.swing.JButton();
        Bnt_9 = new javax.swing.JButton();
        Bnt_0 = new javax.swing.JButton();
        Bnt_Aceptar = new javax.swing.JButton();
        Bnt_Borrar = new javax.swing.JButton();
        Bnt_Cancelar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        Bnt_Ingresar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_Saldo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Panel_Opcion = new javax.swing.JPanel();
        txt_Opcion = new javax.swing.JLabel();
        txt_Cantidad = new javax.swing.JLabel();
        Bnt_Depositar = new javax.swing.JButton();
        Bnt_Retirar = new javax.swing.JButton();
        Bnt_Salir = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jButton11.setText("jButton11");

        jButton16.setText("jButton16");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        Bnt_2.setBackground(new java.awt.Color(153, 153, 153));
        Bnt_2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Bnt_2.setText("2");
        Bnt_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Bnt_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_2ActionPerformed(evt);
            }
        });

        Bnt_3.setBackground(new java.awt.Color(153, 153, 153));
        Bnt_3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Bnt_3.setText("3");
        Bnt_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Bnt_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_3ActionPerformed(evt);
            }
        });

        Bnt_1.setBackground(new java.awt.Color(153, 153, 153));
        Bnt_1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Bnt_1.setText("1");
        Bnt_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Bnt_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_1ActionPerformed(evt);
            }
        });

        Bnt_4.setBackground(new java.awt.Color(153, 153, 153));
        Bnt_4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Bnt_4.setText("4");
        Bnt_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Bnt_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_4ActionPerformed(evt);
            }
        });

        Bnt_5.setBackground(new java.awt.Color(153, 153, 153));
        Bnt_5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Bnt_5.setText("5");
        Bnt_5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Bnt_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_5ActionPerformed(evt);
            }
        });

        Bnt_6.setBackground(new java.awt.Color(153, 153, 153));
        Bnt_6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Bnt_6.setText("6");
        Bnt_6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Bnt_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_6ActionPerformed(evt);
            }
        });

        Bnt_7.setBackground(new java.awt.Color(153, 153, 153));
        Bnt_7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Bnt_7.setText("7");
        Bnt_7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Bnt_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_7ActionPerformed(evt);
            }
        });

        Bnt_8.setBackground(new java.awt.Color(153, 153, 153));
        Bnt_8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Bnt_8.setText("8");
        Bnt_8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Bnt_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_8ActionPerformed(evt);
            }
        });

        Bnt_9.setBackground(new java.awt.Color(153, 153, 153));
        Bnt_9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Bnt_9.setText("9");
        Bnt_9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Bnt_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_9ActionPerformed(evt);
            }
        });

        Bnt_0.setBackground(new java.awt.Color(153, 153, 153));
        Bnt_0.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Bnt_0.setText("0");
        Bnt_0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Bnt_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_0ActionPerformed(evt);
            }
        });

        Bnt_Aceptar.setBackground(new java.awt.Color(0, 255, 0));
        Bnt_Aceptar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Bnt_Aceptar.setText("Aceptar");
        Bnt_Aceptar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Bnt_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_AceptarActionPerformed(evt);
            }
        });

        Bnt_Borrar.setBackground(new java.awt.Color(255, 255, 0));
        Bnt_Borrar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Bnt_Borrar.setText("Borrar");
        Bnt_Borrar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Bnt_Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_BorrarActionPerformed(evt);
            }
        });

        Bnt_Cancelar.setBackground(new java.awt.Color(255, 0, 0));
        Bnt_Cancelar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Bnt_Cancelar.setText("Cancelar");
        Bnt_Cancelar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Bnt_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_CancelarActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(Bnt_1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bnt_2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bnt_3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(Bnt_4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bnt_5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bnt_6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(Bnt_7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bnt_0, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(Bnt_8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bnt_9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bnt_Borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bnt_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bnt_Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(Bnt_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bnt_Borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bnt_Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bnt_2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bnt_3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bnt_1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bnt_5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bnt_6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bnt_4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bnt_8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bnt_9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bnt_7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bnt_0, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Bnt_Ingresar.setBackground(new java.awt.Color(0, 102, 102));
        Bnt_Ingresar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Bnt_Ingresar.setText("Ingresar");
        Bnt_Ingresar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Bnt_Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_IngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bnt_Ingresar, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Bnt_Ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PERÚ BANK");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel7.setBackground(new java.awt.Color(0, 255, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel3.setText("Usuario:");

        txt_Nombre.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        txt_Nombre.setText("Nombre");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel5.setText("Saldo:");

        txt_Saldo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        txt_Saldo.setText("$ 0.00");

        jLabel7.setBackground(new java.awt.Color(0, 102, 102));
        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel7.setText("Depositar");

        jLabel8.setBackground(new java.awt.Color(0, 102, 102));
        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel8.setText("Retirar");

        jLabel9.setBackground(new java.awt.Color(0, 102, 102));
        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel9.setText("Salir");

        Panel_Opcion.setBackground(new java.awt.Color(204, 255, 204));
        Panel_Opcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0), 2));

        txt_Opcion.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        txt_Opcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_Opcion.setText("Opcion");
        txt_Opcion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txt_Cantidad.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        txt_Cantidad.setText("Cantidad");
        txt_Cantidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));

        javax.swing.GroupLayout Panel_OpcionLayout = new javax.swing.GroupLayout(Panel_Opcion);
        Panel_Opcion.setLayout(Panel_OpcionLayout);
        Panel_OpcionLayout.setHorizontalGroup(
            Panel_OpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_OpcionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_OpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Opcion, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                    .addComponent(txt_Cantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Panel_OpcionLayout.setVerticalGroup(
            Panel_OpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_OpcionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_Opcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Cantidad)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(Panel_Opcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Nombre))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txt_Saldo)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_Nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_Saldo))
                .addGap(55, 55, 55)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(jLabel9))
                    .addComponent(Panel_Opcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Bnt_Depositar.setBackground(new java.awt.Color(0, 0, 0));
        Bnt_Depositar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Bnt_Depositar.setForeground(new java.awt.Color(255, 255, 255));
        Bnt_Depositar.setText("<");
        Bnt_Depositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_DepositarActionPerformed(evt);
            }
        });

        Bnt_Retirar.setBackground(new java.awt.Color(0, 0, 0));
        Bnt_Retirar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Bnt_Retirar.setForeground(new java.awt.Color(255, 255, 255));
        Bnt_Retirar.setText("<");
        Bnt_Retirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_RetirarActionPerformed(evt);
            }
        });

        Bnt_Salir.setBackground(new java.awt.Color(0, 0, 0));
        Bnt_Salir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Bnt_Salir.setForeground(new java.awt.Color(255, 255, 255));
        Bnt_Salir.setText("<");
        Bnt_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bnt_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bnt_Retirar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bnt_Depositar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Bnt_Depositar)
                        .addGap(18, 18, 18)
                        .addComponent(Bnt_Retirar)
                        .addGap(37, 37, 37)
                        .addComponent(Bnt_Salir)
                        .addGap(33, 33, 33))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(18, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void Bnt_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_1ActionPerformed
      if(txt_Cantidad.getText().equals(" ")){
      txt_Cantidad.setToolTipText("");
      NuevoNumero =txt_Cantidad.getText()+ "1";
      txt_Cantidad.setText(NuevoNumero);
      }else{
      NuevoNumero = txt_Cantidad.getText()+ "1";
      txt_Cantidad.setText(NuevoNumero);
      }
    }//GEN-LAST:event_Bnt_1ActionPerformed
  
  
    private void Bnt_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_4ActionPerformed
      if(txt_Cantidad.getText().equals(" ")){
      txt_Cantidad.setToolTipText("");
      NuevoNumero =txt_Cantidad.getText()+ "4";
      txt_Cantidad.setText(NuevoNumero);
      }else{
      NuevoNumero = txt_Cantidad.getText()+ "4";
      txt_Cantidad.setText(NuevoNumero);
      }

        
    }//GEN-LAST:event_Bnt_4ActionPerformed
    
    
     
    private void Bnt_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_7ActionPerformed
       if(txt_Cantidad.getText().equals(" ")){
      txt_Cantidad.setToolTipText("");
      NuevoNumero =txt_Cantidad.getText()+ "7";
      txt_Cantidad.setText(NuevoNumero);
      }else{
      NuevoNumero = txt_Cantidad.getText()+ "7";
      txt_Cantidad.setText(NuevoNumero);
      }

    }//GEN-LAST:event_Bnt_7ActionPerformed
   
  
   
    private void Bnt_BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_BorrarActionPerformed
        txt_Cantidad.setText(txt_Cantidad.getText().substring(0,txt_Cantidad.getText().length() -1));
        if(txt_Cantidad.getText().equals("")){
            txt_Cantidad.setText(" ");
        }
    }//GEN-LAST:event_Bnt_BorrarActionPerformed

    private void Bnt_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_CancelarActionPerformed
        txt_Cantidad.setText(" ");
    }//GEN-LAST:event_Bnt_CancelarActionPerformed
 //  [Boton depositar]  //
    private void Bnt_DepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_DepositarActionPerformed
        OpcionDepositar = true;
        Bnt_Depositar.setEnabled(false);
        Bnt_Retirar.setEnabled(false);
        Panel_Opcion.setVisible(true);
        
        txt_Opcion.setText(" [Deposito] -Ingrese una cantidad-");
        
        Bnt_1.setEnabled(true);
        Bnt_2.setEnabled(true);
        Bnt_3.setEnabled(true);
        Bnt_4.setEnabled(true);
        Bnt_5.setEnabled(true);
        Bnt_6.setEnabled(true);
        Bnt_7.setEnabled(true);
        Bnt_8.setEnabled(true);
        Bnt_9.setEnabled(true);
        Bnt_0.setEnabled(true);
        
        Bnt_Cancelar.setEnabled(true);
        Bnt_Borrar.setEnabled(true);
        Bnt_Aceptar.setEnabled(true);
        
    }//GEN-LAST:event_Bnt_DepositarActionPerformed
//  [Boton Retirar]  //
    private void Bnt_RetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_RetirarActionPerformed
         OpcionRetirar = true;
        Bnt_Depositar.setEnabled(false);
        Bnt_Retirar.setEnabled(false);
        Panel_Opcion.setVisible(true);
        
        txt_Opcion.setText(" [Retiro] -Ingrese una cantidad-");
        
        Bnt_1.setEnabled(true);
        Bnt_2.setEnabled(true);
        Bnt_3.setEnabled(true);
        Bnt_4.setEnabled(true);
        Bnt_5.setEnabled(true);
        Bnt_6.setEnabled(true);
        Bnt_7.setEnabled(true);
        Bnt_8.setEnabled(true);
        Bnt_9.setEnabled(true);
        Bnt_0.setEnabled(true);
        
        Bnt_Cancelar.setEnabled(true);
        Bnt_Borrar.setEnabled(true);
        Bnt_Aceptar.setEnabled(true);
    }//GEN-LAST:event_Bnt_RetirarActionPerformed
//  [Boton Salir]  //
    private void Bnt_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_SalirActionPerformed
       if(OpcionDepositar == true || OpcionRetirar == true){
        OpcionDepositar = false;
        OpcionRetirar = false;
        
        Panel_Opcion.setVisible(false);
        Bnt_Depositar.setEnabled(true);
        Bnt_Retirar.setEnabled(true);
        
        Bnt_1.setEnabled(false);
        Bnt_2.setEnabled(false);
        Bnt_3.setEnabled(false);
        Bnt_4.setEnabled(false);
        Bnt_5.setEnabled(false);
        Bnt_6.setEnabled(false);
        Bnt_7.setEnabled(false);
        Bnt_8.setEnabled(false);
        Bnt_9.setEnabled(false);
        Bnt_0.setEnabled(false);
        
        Bnt_Cancelar.setEnabled(false);
        Bnt_Borrar.setEnabled(false);
        Bnt_Aceptar.setEnabled(false);
        
        txt_Cantidad.setText(" ");
        }
        else{
        JOptionPane.showMessageDialog(null, "Gracias vuelva pronto");}
       System.exit(0);
    }//GEN-LAST:event_Bnt_SalirActionPerformed
// [Boton Ingresar] //
    private void Bnt_IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_IngresarActionPerformed
      txt_Nombre.setText(JOptionPane.showInputDialog("Ingrese su nombre."));
      Bnt_Ingresar.setEnabled(false);
              
      Bnt_Depositar.setEnabled(true);
      Bnt_Retirar.setEnabled(true);
      Bnt_Salir.setEnabled(true);
    }//GEN-LAST:event_Bnt_IngresarActionPerformed

    private void Bnt_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_9ActionPerformed
      if(txt_Cantidad.getText().equals(" ")){
      txt_Cantidad.setToolTipText("");
      NuevoNumero =txt_Cantidad.getText()+ "9";
      txt_Cantidad.setText(NuevoNumero);
      }else{
      NuevoNumero = txt_Cantidad.getText()+ "9";
      txt_Cantidad.setText(NuevoNumero);
      }

    }//GEN-LAST:event_Bnt_9ActionPerformed

    private void Bnt_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_AceptarActionPerformed
         if(txt_Cantidad.getText().equals(" ")){
    OpcionDepositar = false;
    OpcionRetirar = false;
    
    Panel_Opcion.setVisible(false);
    Bnt_Depositar.setEnabled(true);
    Bnt_Retirar.setEnabled(true);
    txt_Cantidad.setText(" ");
    
    Bnt_1.setEnabled(false);
    Bnt_2.setEnabled(false);
    Bnt_3.setEnabled(false);
    Bnt_4.setEnabled(false);
    Bnt_5.setEnabled(false);
    Bnt_6.setEnabled(false);
    Bnt_7.setEnabled(false);
    Bnt_8.setEnabled(false);
    Bnt_9.setEnabled(false);
    Bnt_0.setEnabled(false);
        
    Bnt_Cancelar.setEnabled(false);
    Bnt_Borrar.setEnabled(false);
    Bnt_Aceptar.setEnabled(false);

    }
    else if(OpcionDepositar == true){
    OpcionDepositar = false;
    NuevaCantidad = Double.parseDouble(String.valueOf (txt_Cantidad.getText()));
    atm.Depositar(NuevaCantidad);
    
    txt_Saldo.setText(String.valueOf(atm.ObtenerSaldo()));
    Panel_Opcion.setVisible(false);
    txt_Cantidad.setText(" ");
    Bnt_Depositar.setEnabled(true);
    Bnt_Retirar.setEnabled(true);
    
    Bnt_1.setEnabled(false);
    Bnt_2.setEnabled(false);
    Bnt_3.setEnabled(false);
    Bnt_4.setEnabled(false);
    Bnt_5.setEnabled(false);
    Bnt_6.setEnabled(false);
    Bnt_7.setEnabled(false);
    Bnt_8.setEnabled(false);
    Bnt_9.setEnabled(false);
    Bnt_0.setEnabled(false);
        
    Bnt_Cancelar.setEnabled(false);
    Bnt_Borrar.setEnabled(false);
    Bnt_Aceptar.setEnabled(false);
    } 
    else if(OpcionRetirar == true){
    OpcionRetirar = false;
    NuevaCantidad = Double.parseDouble(String.valueOf (txt_Cantidad.getText()));
    atm.Retirar(NuevaCantidad);
    txt_Saldo.setText(String.valueOf(atm.ObtenerSaldo()));
    
    Panel_Opcion.setVisible(false);
    txt_Cantidad.setText(" ");
    Bnt_Depositar.setEnabled(true);
    Bnt_Retirar.setEnabled(true);
    
    Bnt_1.setEnabled(false);
    Bnt_2.setEnabled(false);
    Bnt_3.setEnabled(false);
    Bnt_4.setEnabled(false);
    Bnt_5.setEnabled(false);
    Bnt_6.setEnabled(false);
    Bnt_7.setEnabled(false);
    Bnt_8.setEnabled(false);
    Bnt_9.setEnabled(false);
    Bnt_0.setEnabled(false);
        
    Bnt_Cancelar.setEnabled(false);
    Bnt_Borrar.setEnabled(false);
    Bnt_Aceptar.setEnabled(false);
    
    }
    }//GEN-LAST:event_Bnt_AceptarActionPerformed

    private void Bnt_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_6ActionPerformed
        if(txt_Cantidad.getText().equals(" ")){
      txt_Cantidad.setToolTipText("");
      NuevoNumero =txt_Cantidad.getText()+ "6";
      txt_Cantidad.setText(NuevoNumero);
      }else{
      NuevoNumero = txt_Cantidad.getText()+ "6";
      txt_Cantidad.setText(NuevoNumero);
      }
    }//GEN-LAST:event_Bnt_6ActionPerformed

    private void Bnt_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_8ActionPerformed
          if(txt_Cantidad.getText().equals(" ")){
      txt_Cantidad.setToolTipText("");
      NuevoNumero =txt_Cantidad.getText()+ "8";
      txt_Cantidad.setText(NuevoNumero);
      }else{
      NuevoNumero = txt_Cantidad.getText()+ "8";
      txt_Cantidad.setText(NuevoNumero);
      }
    }//GEN-LAST:event_Bnt_8ActionPerformed

    private void Bnt_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_5ActionPerformed
  if(txt_Cantidad.getText().equals(" ")){
      txt_Cantidad.setToolTipText("");
      NuevoNumero =txt_Cantidad.getText()+ "5";
      txt_Cantidad.setText(NuevoNumero);
      }else{
      NuevoNumero = txt_Cantidad.getText()+ "5";
      txt_Cantidad.setText(NuevoNumero);
      
  }    }//GEN-LAST:event_Bnt_5ActionPerformed

    private void Bnt_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_0ActionPerformed
         if(txt_Cantidad.getText().equals(" ")){
      txt_Cantidad.setToolTipText("");
      NuevoNumero =txt_Cantidad.getText()+ "0";
      txt_Cantidad.setText(NuevoNumero);
      }else{
      NuevoNumero = txt_Cantidad.getText()+ "0";
      txt_Cantidad.setText(NuevoNumero);
      }
    }//GEN-LAST:event_Bnt_0ActionPerformed

    private void Bnt_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_3ActionPerformed
         if(txt_Cantidad.getText().equals(" ")){
      txt_Cantidad.setToolTipText("");
      NuevoNumero =txt_Cantidad.getText()+ "3";
      txt_Cantidad.setText(NuevoNumero);
      }else{
      NuevoNumero = txt_Cantidad.getText()+ "3";
      txt_Cantidad.setText(NuevoNumero);
      }
    }//GEN-LAST:event_Bnt_3ActionPerformed

    private void Bnt_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_2ActionPerformed
          if(txt_Cantidad.getText().equals(" ")){
      txt_Cantidad.setToolTipText("");
      NuevoNumero =txt_Cantidad.getText()+ "2";
      txt_Cantidad.setText(NuevoNumero);
      }else{
      NuevoNumero = txt_Cantidad.getText()+ "2";
      txt_Cantidad.setText(NuevoNumero);
      }
    }//GEN-LAST:event_Bnt_2ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazBanco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bnt_0;
    private javax.swing.JButton Bnt_1;
    private javax.swing.JButton Bnt_2;
    private javax.swing.JButton Bnt_3;
    private javax.swing.JButton Bnt_4;
    private javax.swing.JButton Bnt_5;
    private javax.swing.JButton Bnt_6;
    private javax.swing.JButton Bnt_7;
    private javax.swing.JButton Bnt_8;
    private javax.swing.JButton Bnt_9;
    private javax.swing.JButton Bnt_Aceptar;
    private javax.swing.JButton Bnt_Borrar;
    private javax.swing.JButton Bnt_Cancelar;
    private javax.swing.JButton Bnt_Depositar;
    private javax.swing.JButton Bnt_Ingresar;
    private javax.swing.JButton Bnt_Retirar;
    private javax.swing.JButton Bnt_Salir;
    private javax.swing.JPanel Panel_Opcion;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton16;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel txt_Cantidad;
    private javax.swing.JLabel txt_Nombre;
    private javax.swing.JLabel txt_Opcion;
    private javax.swing.JLabel txt_Saldo;
    // End of variables declaration//GEN-END:variables
}
